/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:e39c3c02-f23c-4a69-ae31-5a6238baed6f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_CXOmIOeAI",
    "aws_user_pools_web_client_id": "7p3rftqtgculfl3ejghein0nq5",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "usersdb-develop",
            "region": "eu-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ngnzjooxwbckja7mom3z5btkae.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rofypapnejcl5lfpoeb6dd6c74",
    "aws_cloud_logic_custom": [
        {
            "name": "userservices",
            "endpoint": "https://2sw33mo29d.execute-api.eu-west-2.amazonaws.com/develop",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
